get '/sign_out', to: 'session#destroy'
post '/registration/create', to: 'registration#create'
post '/session', to: 'session#create'
get '/registration', to: 'registration#index'
get '/home', to: 'home#index'
get '/', to: 'home#index'
